In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline 

In [3]:
from sklearn.datasets import make_classification

In [8]:
x,y=make_classification(n_samples=1000,n_features=3,n_classes=2,random_state=42,n_informative=3,
    n_redundant=0)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

# Adaboost Algo 

In [13]:
from sklearn.ensemble import AdaBoostClassifier 

In [14]:
ada=AdaBoostClassifier(n_estimators=20)

In [15]:
ada.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=20)

In [16]:
y_pred=ada.predict(x_test)

In [17]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [19]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.88
[[137  23]
 [ 13 127]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.88       160
           1       0.85      0.91      0.88       140

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



# Gradienct boosting algo 

In [20]:
from sklearn.ensemble import GradientBoostingClassifier

In [21]:
gbc=GradientBoostingClassifier(n_estimators=50)

In [22]:
gbc.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=50)

In [23]:
y_pred=gbc.predict(x_test)

In [24]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.91
[[144  16]
 [ 11 129]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       160
           1       0.89      0.92      0.91       140

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



# XG boost 

In [25]:
!pip install xgboost

In [31]:
import xgboost as xb

In [32]:
cgb_model=xb.XGBClassifier()

In [33]:
cgb_model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [34]:
y_pred=cgb_model.predict(x_test)

In [35]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.94
[[149  11]
 [  7 133]]
              precision    recall  f1-score   support

           0       0.96      0.93      0.94       160
           1       0.92      0.95      0.94       140

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



# Hyper parameter tuning using grid search cv 

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
classifier=xb.XGBClassifier()

In [38]:
parameters = {
    'max_depth': range (2, 10, 1),
    'n_estimators': range(60, 220, 40),
    'learning_rate': [0.1, 0.01, 0.05]
}

In [39]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5,scoring='accuracy',verbose=3)

In [40]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits
[CV 1/5] END learning_rate=0.1, max_depth=2, n_estimators=60;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.1, max_depth=2, n_estimators=60;, score=0.943 total time=   0.0s
[CV 3/5] END learning_rate=0.1, max_depth=2, n_estimators=60;, score=0.936 total time=   0.0s
[CV 4/5] END learning_rate=0.1, max_depth=2, n_estimators=60;, score=0.943 total time=   0.0s
[CV 5/5] END learning_rate=0.1, max_depth=2, n_estimators=60;, score=0.950 total time=   0.0s
[CV 1/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.929 total time=   0.0s
[CV 4/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.957 total time=   0.0s
[CV 5/5] END learning_rate=0.1, max_depth=2, n_estimators=100;, score=0.979 total time= 

[CV 3/5] END learning_rate=0.1, max_depth=6, n_estimators=100;, score=0.943 total time=   0.0s
[CV 4/5] END learning_rate=0.1, max_depth=6, n_estimators=100;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.1, max_depth=6, n_estimators=100;, score=0.986 total time=   0.0s
[CV 1/5] END learning_rate=0.1, max_depth=6, n_estimators=140;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.1, max_depth=6, n_estimators=140;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.1, max_depth=6, n_estimators=140;, score=0.943 total time=   0.0s
[CV 4/5] END learning_rate=0.1, max_depth=6, n_estimators=140;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.1, max_depth=6, n_estimators=140;, score=0.986 total time=   0.0s
[CV 1/5] END learning_rate=0.1, max_depth=6, n_estimators=180;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.1, max_depth=6, n_estimators=180;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.1, max_depth=6, n_est

[CV 1/5] END learning_rate=0.01, max_depth=2, n_estimators=180;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.01, max_depth=2, n_estimators=180;, score=0.914 total time=   0.0s
[CV 3/5] END learning_rate=0.01, max_depth=2, n_estimators=180;, score=0.929 total time=   0.0s
[CV 4/5] END learning_rate=0.01, max_depth=2, n_estimators=180;, score=0.914 total time=   0.0s
[CV 5/5] END learning_rate=0.01, max_depth=2, n_estimators=180;, score=0.936 total time=   0.0s
[CV 1/5] END learning_rate=0.01, max_depth=3, n_estimators=60;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.01, max_depth=3, n_estimators=60;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.01, max_depth=3, n_estimators=60;, score=0.950 total time=   0.0s
[CV 4/5] END learning_rate=0.01, max_depth=3, n_estimators=60;, score=0.943 total time=   0.0s
[CV 5/5] END learning_rate=0.01, max_depth=3, n_estimators=60;, score=0.950 total time=   0.0s
[CV 1/5] END learning_rate=0.01, max_depth=3,

[CV 2/5] END learning_rate=0.01, max_depth=7, n_estimators=60;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.01, max_depth=7, n_estimators=60;, score=0.950 total time=   0.0s
[CV 4/5] END learning_rate=0.01, max_depth=7, n_estimators=60;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.01, max_depth=7, n_estimators=60;, score=0.957 total time=   0.0s
[CV 1/5] END learning_rate=0.01, max_depth=7, n_estimators=100;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.01, max_depth=7, n_estimators=100;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.01, max_depth=7, n_estimators=100;, score=0.943 total time=   0.0s
[CV 4/5] END learning_rate=0.01, max_depth=7, n_estimators=100;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.01, max_depth=7, n_estimators=100;, score=0.957 total time=   0.0s
[CV 1/5] END learning_rate=0.01, max_depth=7, n_estimators=140;, score=0.950 total time=   0.0s
[CV 2/5] END learning_rate=0.01, max_depth=7

[CV 1/5] END learning_rate=0.05, max_depth=3, n_estimators=140;, score=0.943 total time=   0.0s
[CV 2/5] END learning_rate=0.05, max_depth=3, n_estimators=140;, score=0.957 total time=   0.0s
[CV 3/5] END learning_rate=0.05, max_depth=3, n_estimators=140;, score=0.936 total time=   0.0s
[CV 4/5] END learning_rate=0.05, max_depth=3, n_estimators=140;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.05, max_depth=3, n_estimators=140;, score=0.979 total time=   0.0s
[CV 1/5] END learning_rate=0.05, max_depth=3, n_estimators=180;, score=0.964 total time=   0.0s
[CV 2/5] END learning_rate=0.05, max_depth=3, n_estimators=180;, score=0.964 total time=   0.0s
[CV 3/5] END learning_rate=0.05, max_depth=3, n_estimators=180;, score=0.929 total time=   0.0s
[CV 4/5] END learning_rate=0.05, max_depth=3, n_estimators=180;, score=0.964 total time=   0.0s
[CV 5/5] END learning_rate=0.05, max_depth=3, n_estimators=180;, score=0.979 total time=   0.0s
[CV 1/5] END learning_rate=0.05, max_dep

[CV 3/5] END learning_rate=0.05, max_depth=7, n_estimators=180;, score=0.943 total time=   0.0s
[CV 4/5] END learning_rate=0.05, max_depth=7, n_estimators=180;, score=0.971 total time=   0.0s
[CV 5/5] END learning_rate=0.05, max_depth=7, n_estimators=180;, score=0.986 total time=   0.0s
[CV 1/5] END learning_rate=0.05, max_depth=8, n_estimators=60;, score=0.957 total time=   0.0s
[CV 2/5] END learning_rate=0.05, max_depth=8, n_estimators=60;, score=0.964 total time=   0.0s
[CV 3/5] END learning_rate=0.05, max_depth=8, n_estimators=60;, score=0.929 total time=   0.0s
[CV 4/5] END learning_rate=0.05, max_depth=8, n_estimators=60;, score=0.971 total time=   0.0s
[CV 5/5] END learning_rate=0.05, max_depth=8, n_estimators=60;, score=0.979 total time=   0.0s
[CV 1/5] END learning_rate=0.05, max_depth=8, n_estimators=100;, score=0.957 total time=   0.0s
[CV 2/5] END learning_rate=0.05, max_depth=8, n_estimators=100;, score=0.964 total time=   0.0s
[CV 3/5] END learning_rate=0.05, max_depth=8,

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.1, 0.01, 0.05],
                         'max_depth': range(2, 10),
                         'n_estimators': range(60, 220, 40)},
             scoring='accuracy', verbose=3)

In [41]:
clf.best_params_

{'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 100}

In [43]:
y_pred=clf.predict(x_test)

In [44]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.94
[[150  10]
 [  8 132]]
              precision    recall  f1-score   support

           0       0.95      0.94      0.94       160
           1       0.93      0.94      0.94       140

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300

