In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 


In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset=load_iris()

In [6]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [15]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [16]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
df['target']=dataset.target

In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [20]:
df['target'].unique()

array([0, 1, 2])

# Binary Classification using Logistic Regression 

In [22]:
df_copy=df[df['target']!=2]

In [25]:
df_copy.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [26]:
df_copy['target'].unique()


array([0, 1])

In [27]:
from sklearn.model_selection import train_test_split 


In [29]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

# Model trainnig 

In [35]:
from sklearn.linear_model import LogisticRegression 

In [36]:
class_lg=LogisticRegression()

In [37]:
class_lg.fit(x_train,y_train)

LogisticRegression()

In [38]:
y_pred=class_lg.predict(x_test)

In [39]:
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

# Accuracy, confusion metrics, classification report

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [42]:
print('Accuracy:',accuracy_score(y_test,y_pred))

Accuracy: 1.0


In [47]:
print(confusion_matrix(y_test,y_pred))

[[10  0]
 [ 0 10]]


In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Cross Validation in LG 

In [52]:
from sklearn.model_selection import KFold

In [55]:
cv=KFold(n_splits=5)

In [56]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [57]:
from sklearn.model_selection import cross_val_score 

In [61]:
# Scores fro all 5 cross validation 
scores=cross_val_score(class_lg,x_train,y_train,scoring='accuracy',cv=cv)

In [63]:
final_score=np.mean(scores)
final_score

1.0

In [65]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
x,y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [66]:
from sklearn.model_selection import train_test_split 

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [68]:
complex_class_model=LogisticRegression(max_iter=200)

In [69]:
complex_class_model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [70]:
y_pred=complex_class_model.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [72]:
print('Accuracy:',accuracy_score(y_test,y_pred))

Accuracy: 0.805


In [73]:
print(confusion_matrix(y_test,y_pred))

[[83 11]
 [28 78]]


In [74]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.88      0.81        94
           1       0.88      0.74      0.80       106

    accuracy                           0.81       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.82      0.81      0.80       200



# Cross validation with 5 splits 

In [75]:
cv1=KFold(n_splits=5)

In [76]:
# Scores fro all 5 cross validation 
scores1=cross_val_score(complex_class_model,x_train,y_train,scoring='accuracy',cv=cv1)

In [77]:
scores1

array([0.825  , 0.79375, 0.7875 , 0.79375, 0.8625 ])

# Hyper parametr tuning 

In [78]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [79]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [81]:
#model training with hyper parameter tuning 
from sklearn.model_selection import GridSearchCV


In [102]:
parameters={'penalty': ('l1','l2','elasticnet'),'C':[1,10,20,30],
              'solver': ('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga') }

In [103]:
classifier=LogisticRegression()

In [104]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [105]:
#spliting the data into train and test 
clf.fit(x_train,y_train)

C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linea

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')})

In [106]:
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [107]:
clf.best_score_


0.8087500000000001

# Model Making 

In [108]:
clas_model=LogisticRegression(penalty='l2',C=1,solver='liblinear')

In [109]:
clas_model.fit(x_train,y_train)

LogisticRegression(C=1, solver='liblinear')

In [110]:
y_pred=clas_model.predict(x_test)

In [111]:
print('Accuracy',accuracy_score(y_test,y_pred))

Accuracy 0.79


In [112]:
print(confusion_matrix(y_test,y_pred))

[[78 13]
 [29 80]]


In [113]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [114]:
clas_model.predict_proba(x_test)

array([[0.71485303, 0.28514697],
       [0.19557827, 0.80442173],
       [0.12300482, 0.87699518],
       [0.04954665, 0.95045335],
       [0.88697131, 0.11302869],
       [0.74971382, 0.25028618],
       [0.97938961, 0.02061039],
       [0.39248274, 0.60751726],
       [0.59925065, 0.40074935],
       [0.39231798, 0.60768202],
       [0.2037125 , 0.7962875 ],
       [0.80211941, 0.19788059],
       [0.86290647, 0.13709353],
       [0.92584573, 0.07415427],
       [0.00129826, 0.99870174],
       [0.04143876, 0.95856124],
       [0.56029931, 0.43970069],
       [0.89201375, 0.10798625],
       [0.29153657, 0.70846343],
       [0.0084863 , 0.9915137 ],
       [0.71863447, 0.28136553],
       [0.50833434, 0.49166566],
       [0.76167355, 0.23832645],
       [0.73140648, 0.26859352],
       [0.10125931, 0.89874069],
       [0.03997952, 0.96002048],
       [0.57682431, 0.42317569],
       [0.00529658, 0.99470342],
       [0.03077926, 0.96922074],
       [0.96041917, 0.03958083],
       [0.

# Randomized search CV 

In [115]:
from sklearn.model_selection import RandomizedSearchCV


In [116]:
parameters_1={'penalty': ('l1','l2','elasticnet'),'C':[1,10,20,30],
              'solver': ('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga') }

In [117]:
class_1_model=LogisticRegression()

In [118]:
clf_ran=RandomizedSearchCV(class_1_model,param_distributions=parameters_1,n_iter=10,scoring='accuracy')

In [119]:
clf_ran.fit(x_train,y_train)

C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
15 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\chintan Gehlot\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1169, in fit
    solver = _check_solver(s

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ('lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga')},
                   scoring='accuracy')

In [120]:
clf_ran.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 10}

In [121]:
clf_ran.best_score_

0.8087500000000001

# Multiclass Classification

In [122]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [124]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=56)

In [125]:
multi_lg_model=LogisticRegression(multi_class='ovr')

In [126]:
multi_lg_model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [127]:
y_pred=multi_lg_model.predict(x_test)

In [128]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [130]:
print('Accuracy:',accuracy_score(y_test,y_pred))

Accuracy: 0.715


In [131]:
print(confusion_matrix(y_test,y_pred))

[[50 12  3]
 [ 8 46 15]
 [15  4 47]]


In [132]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.68      0.77      0.72        65
           1       0.74      0.67      0.70        69
           2       0.72      0.71      0.72        66

    accuracy                           0.71       200
   macro avg       0.72      0.72      0.71       200
weighted avg       0.72      0.71      0.71       200

